#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class SurrogateKind(object):
    KRIGING = 0
    KPLS = 1
    KPLSK = 2
    LS = 3
    QP = 4

    _VALUES_TO_NAMES = {
        0: "KRIGING",
        1: "KPLS",
        2: "KPLSK",
        3: "LS",
        4: "QP",
    }

    _NAMES_TO_VALUES = {
        "KRIGING": 0,
        "KPLS": 1,
        "KPLSK": 2,
        "LS": 3,
        "QP": 4,
    }
fix_spec(all_structs)
del all_structs
