inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'app/lib/whats_opt/services/*.rb'
  TargetRubyVersion: 3.0

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods