# -*- coding: utf-8 -*-
"""
  disc1_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analyses: 109

import numpy as np
from openmdao.api import ExplicitComponent

class Disc1Base(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Disc1 discipline """

    def setup(self):
		
        self.add_input('y2', val=1.0, desc='')
        self.add_input('x', val=1.0, desc='')
        self.add_input('z', val=np.ones((2,)), desc='')
		
        self.add_output('y1', val=1.0, desc='')
#        self.declare_partials('*', '*')
		
#    def compute(self, inputs, outputs):
#        """ Disc1 computation """
    
#        outputs['y1'] = 1.0   
				
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Disc1 """
    
   		
#       	partials['y1', 'y2'] = np.zeros((1, 1))
#       	partials['y1', 'x'] = np.zeros((1, 1))
#       	partials['y1', 'z'] = np.zeros((1, 2))        

        