# -*- coding: utf-8 -*-
"""
  functions_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 109

import numpy as np
from openmdao.api import ExplicitComponent

class FunctionsBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Functions discipline """

    def setup(self):
		
        self.add_input('z', val=np.ones((2,)), desc='')
        self.add_input('y1', val=1.0, desc='')
        self.add_input('y2', val=1.0, desc='')
        self.add_input('x', val=1.0, desc='')
		
        self.add_output('obj', val=1.0, desc='')
        self.add_output('g1', val=1.0, desc='constraint')
        self.add_output('g2', val=1.0, desc='')
#        self.declare_partials('*', '*')
		
#    def compute(self, inputs, outputs):
#        """ Functions computation """
    
#        outputs['obj'] = 1.0 
#        outputs['g1'] = 1.0 
#        outputs['g2'] = 1.0   
				
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Functions """
    
   		
#       	partials['obj', 'z'] = np.zeros((1, 2))
#       	partials['obj', 'y1'] = np.zeros((1, 1))
#       	partials['obj', 'y2'] = np.zeros((1, 1))
#       	partials['obj', 'x'] = np.zeros((1, 1))
   		
#       	partials['g1', 'z'] = np.zeros((1, 2))
#       	partials['g1', 'y1'] = np.zeros((1, 1))
#       	partials['g1', 'y2'] = np.zeros((1, 1))
#       	partials['g1', 'x'] = np.zeros((1, 1))
   		
#       	partials['g2', 'z'] = np.zeros((1, 2))
#       	partials['g2', 'y1'] = np.zeros((1, 1))
#       	partials['g2', 'y2'] = np.zeros((1, 1))
#       	partials['g2', 'x'] = np.zeros((1, 1))        

        