# -*- coding: utf-8 -*-
"""
  run_analysis.py generated by WhatsOpt. 
"""
from openmdao.api import Problem
from sellar import Sellar

pb = Problem(Sellar())
pb.setup()  

pb.run_model()   
pb.model.list_inputs(print_arrays=True)
pb.model.list_outputs(print_arrays=True)

