# -*- coding: utf-8 -*-
"""
  run_screening.py generated by WhatsOpt. 
"""
import numpy as np
import six
from openmdao.api import Problem, SqliteRecorder, CaseReader
from whatsopt.salib_doe_driver import SalibDoeDriver
from sellar import Sellar

pb = Problem(Sellar())
pb.driver = SalibDriver(sampling_method='LHS', n_cases=100)
case_recorder_filename = 'sellar_screening.sqlite'        
recorder = SqliteRecorder(case_recorder_filename)
pb.driver.add_recorder(recorder)
pb.model.add_recorder(recorder)
pb.model.nonlinear_solver.add_recorder(recorder)


pb.model.add_design_var('x', lower=0, upper=10)
pb.model.add_design_var('z', lower=0, upper=10)

pb.model.add_objective('obj')
pb.model.add_objective('g1')
pb.model.add_objective('g2')
pb.setup()  
pb.run_driver()        

