# -*- coding: utf-8 -*-
"""
  aerodynamics_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 3

import numpy as np
from openmdao.api import ExplicitComponent

class AerodynamicsBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Aerodynamics discipline """

    def setup(self):
		
        self.add_input('ESF', val=1.0, desc='engine scale factor')
        self.add_input('Theta', val=1.0, desc='wing twist')
        self.add_input('WT', val=1.0, desc='total weight')
        self.add_input('x_aer', val=1.0, desc='skin friction coefficient')
        self.add_input('z', val=np.ones((6,)), desc='thickness/chord ratio, altitude, mach number, aspect ratio, wing sweep, wing surface area')
		
        self.add_output('dpdx', val=1.0, desc='pressure gradient')
        self.add_output('D', val=1.0, desc='drag')
        self.add_output('L', val=1.0, desc='lift')
        self.add_output('fin', val=1.0, desc='lift/drag ratio')
		

        