# -*- coding: utf-8 -*-
"""
  con1_esf_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class Con1EsfBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Con1Esf discipline """

    def setup(self):
		
        self.add_input('ESF', val=1.0, desc='')
		
        self.add_output('con1_esf', val=1.0, desc='')
		

        