# -*- coding: utf-8 -*-
"""
  con_theta_inf_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class ConThetaInfBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ConThetaInf discipline """

    def setup(self):
		
        self.add_input('Theta', val=1.0, desc='')
		
        self.add_output('con_Theta_low', val=1.0, desc='')
		

        