# -*- coding: utf-8 -*-
"""
  con_temp_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class ConTempBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ConTemp discipline """

    def setup(self):
		
        self.add_input('Temp', val=1.0, desc='')
		
        self.add_output('con_temp', val=1.0, desc='')
		

        