# -*- coding: utf-8 -*-
"""
  con_dpdx_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class ConDpdxBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ConDpdx discipline """

    def setup(self):
		
        self.add_input('dpdx', val=1.0, desc='')
		
        self.add_output('con_dpdx', val=1.0, desc='')
		

        