# -*- coding: utf-8 -*-
"""
  performance_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 3

import numpy as np
from openmdao.api import ExplicitComponent

class PerformanceBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Performance discipline """

    def setup(self):
		
        self.add_input('SFC', val=1.0, desc='specific fuel consumption')
        self.add_input('WF', val=1.0, desc='fuel weight')
        self.add_input('WT', val=1.0, desc='total weight')
        self.add_input('fin', val=1.0, desc='lift/drag ratio')
        self.add_input('z', val=np.ones((6,)), desc='thickness/chord ratio, altitude, mach number, aspect ratio, wing sweep, wing surface area')
		
        self.add_output('R', val=1.0, desc='mission range')
		

        