# -*- coding: utf-8 -*-
"""
  perfo_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class PerfoBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Perfo discipline """

    def setup(self):
		
        self.add_input('SFC', val=1.0, desc='')
        self.add_input('WF', val=1.0, desc='')
        self.add_input('WT', val=1.0, desc='')
        self.add_input('fin', val=1.0, desc='')
        self.add_input('z', val=np.ones((6,)), desc='')
		
        self.add_output('R', val=1.0, desc='')
		

        