# -*- coding: utf-8 -*-
"""
  propulsion_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 3

import numpy as np
from openmdao.api import ExplicitComponent

class PropulsionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Propulsion discipline """

    def setup(self):
		
        self.add_input('D', val=1.0, desc='drag')
        self.add_input('x_pro', val=1.0, desc='throttle setting')
        self.add_input('z', val=np.ones((6,)), desc='thickness/chord ratio, altitude, mach number, aspect ratio, wing sweep, wing surface area')
		
        self.add_output('DT', val=1.0, desc='throttle setting')
        self.add_output('ESF', val=1.0, desc='engine scale factor')
        self.add_output('Temp', val=1.0, desc='engine temperature')
        self.add_output('WE', val=1.0, desc='engine weight')
        self.add_output('SFC', val=1.0, desc='specific fuel consumption')
		

        