# -*- coding: utf-8 -*-
"""
  sap_propu_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class SapPropuBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate SapPropu discipline """

    def setup(self):
		
        self.add_input('D', val=1.0, desc='')
        self.add_input('x_pro', val=1.0, desc='')
        self.add_input('z', val=np.ones((6,)), desc='')
		
        self.add_output('SFC', val=1.0, desc='')
        self.add_output('ESF', val=1.0, desc='')
        self.add_output('DT', val=1.0, desc='')
        self.add_output('Temp', val=1.0, desc='')
        self.add_output('WE', val=1.0, desc='')
		

        