# -*- coding: utf-8 -*-
"""
  sap_struc_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 47

import numpy as np
from openmdao.api import ExplicitComponent

class SapStrucBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate SapStruc discipline """

    def setup(self):
		
        self.add_input('L', val=1.0, desc='')
        self.add_input('WE', val=1.0, desc='')
        self.add_input('x_str', val=np.ones((2,)), desc='')
        self.add_input('z', val=np.ones((6,)), desc='')
		
        self.add_output('WF', val=1.0, desc='')
        self.add_output('WT', val=1.0, desc='')
        self.add_output('sigma', val=np.ones((5,)), desc='')
        self.add_output('Theta', val=1.0, desc='')
		

        