# -*- coding: utf-8 -*-
"""
  structure_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 3

import numpy as np
from openmdao.api import ExplicitComponent

class StructureBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Structure discipline """

    def setup(self):
		
        self.add_input('L', val=1.0, desc='lift')
        self.add_input('WE', val=1.0, desc='engine weight')
        self.add_input('x_str', val=np.ones((2,)), desc='wing taper ratio and winbox x-sectional area')
        self.add_input('z', val=np.ones((6,)), desc='thickness/chord ratio, altitude, mach number, aspect ratio, wing sweep, wing surface area')
		
        self.add_output('Theta', val=1.0, desc='wing twist')
        self.add_output('sigma', val=np.ones((5,)), desc='stress on wing')
        self.add_output('WT', val=1.0, desc='total weight')
        self.add_output('WF', val=1.0, desc='fuel weight')
		

        