# -*- coding: utf-8 -*-
"""
  disc1.py generated by WhatsOpt. 
"""
from disc1_base import Disc1Base
from sellar_conversions import *

class Disc1(Disc1Base):
    """ An OpenMDAO component to encapsulate Disc1 discipline """
		
    def compute(self, inputs, outputs):
        """ Disc1 computation """

        outputs = to_openMDAO_disc1_outputs(to_thrift_disc1_input(inputs))

				
        
