# -*- coding: utf-8 -*-
"""
  functions.py generated by WhatsOpt. 
"""
from functions_base import Functions2Base
from sellar_conversions import *

class Functions(FunctionsBase):
    """ An OpenMDAO component to encapsulate Functions discipline """
		
    def compute(self, inputs, outputs):
        """ Functions computation """

        outputs = to_openmdao_functions_outputs(to_thrift_functions_input(inputs))

				
        
