#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module WhatsOpt
  module SurrogateServer
    module SurrogateKind
      KRIGING = 0
      KPLS = 1
      KPLSK = 2
      LS = 3
      QP = 4
      VALUE_MAP = {0 => "KRIGING", 1 => "KPLS", 2 => "KPLSK", 3 => "LS", 4 => "QP"}
      VALID_VALUES = Set.new([KRIGING, KPLS, KPLSK, LS, QP]).freeze
    end

  end
end
