# -*- coding: utf-8 -*-
"""
  branin_function_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 140

import numpy as np
from openmdao.api import ExplicitComponent

class BraninFunctionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate BraninFunction discipline """

    
    def setup(self):
		
        self.add_input('x1', val=1.0, desc='')
        self.add_input('x2', val=1.0, desc='')
		
        self.add_output('f', val=1.0, desc='')
        self.add_output('g', val=1.0, desc='')
	

        