# -*- coding: utf-8 -*-
/*
  analysis.thrift generated by WhatsOpt. 
*/
namespace py branin

typedef double Float
typedef i32 Integer
typedef list<Float> Vector
typedef list<Integer> IVector
typedef list<Vector> Matrix
typedef list<IVector> IMatrix
typedef list<Matrix> Cube
typedef list<IMatrix> ICube
typedef list<Cube> HyperCube
typedef list<ICube> IHyperCube

struct BraninFunctionInput {
    1: Float x1      
    2: Float x2      
}

struct BraninFunctionOutput {
    1: Float f     
    2: Float g     
}

service Branin {
    BraninFunctionOutput compute_branin_function(1:BraninFunctionInput input)

    void ping()
    oneway void shutdown()
}