# -*- coding: utf-8 -*-
"""
  branin_proxy.py generated by WhatsOpt. 
"""
from .branin import Branin
from .branin_conversions import *

from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol

from branin_base import BraninBase
from branin_function_base import BraninFunctionBase


class BraninFunctionProxy(BraninFunctionBase):
    def __init__(self, proxy):
        super(BraninFunctionProxy, self).__init__()
        self._proxy = proxy
        
    def compute(self, inputs, outputs):
        output = self._proxy.compute_branin_function(to_thrift_branin_function_input(inputs))
        to_openmdao_branin_function_outputs(output, outputs)



class BraninProxy(BraninBase):
    
    def __init__(self):
        super(BraninProxy, self).__init__()
        transport = TSocket.TSocket('localhost', 31400)
        transport = TTransport.TBufferedTransport(transport)
        protocol = TBinaryProtocol.TBinaryProtocol(transport)
        self._proxy = Branin.Client(protocol)
        transport.open()

    
    def create_branin_function(self):
        return BraninFunctionProxy(self._proxy)
    

    def ping(self):
        self._proxy.ping()

    def shutdown(self):
        self._proxy.shutdown()
    