require 'erubi'
require 'tmpdir'
require 'zip'

module WhatsOpt
  
  class OpenmdaoGenerator
    
    attr_accessor :genfiles 
    
    class DisciplineNotFoundException < StandardError
    end
    
    def initialize(mda)
      @mda = mda
      @template_dir = File.join(File.dirname(__FILE__), "templates")
      @genfiles = []
    end
        
    def generate_zip
      zip_filename = 'openmdao_mda.zip'
      stringio = nil
      Dir.mktmpdir("openmdao_#{@mda.name.downcase.tr(" ", "_")}_") do |dir|
        zip_filename = File.basename(dir)+".zip"
        _generate_mda dir
        stringio = Zip::OutputStream.write_buffer do |zio|
          @genfiles.each do |filename|
            zio.put_next_entry(File.join(File.basename(dir), File.basename(filename)))
            File.open(filename) do |f|
              zio.write f.read
            end
          end
        end
      end
      stringio.rewind
      return stringio, zip_filename
    end

    def check_mda_setup
      ok, lines = false, []
      Dir.mktmpdir("check_#{@mda.name.downcase.tr(" ", "_")}_") do |dir|
        _generate_mda dir
        ok, log = _check_mda dir   
        lines = log.lines.map(&:chomp)     
      end
      return ok, lines
    end
    
    def _generate_mda(gendir)
      @mda.disciplines.plain.each do |disc|
        _generate_discipline(disc, gendir)
      end 
      _generate_main(gendir)
    end
    
    def _check_mda(gendir)
      script = File.join(gendir, @mda.py_filename) 
      stdouterr, status = Open3.capture2e('python', script, '--no-n2')
      return status.success?, stdouterr
    end

    def _generate_main gendir
      _generate(@mda.py_filename, 'openmdao_main.py.erb', gendir)
    end
    
    def _generate_discipline(disc, gendir)
      @discipline = disc
      if @discipline
        _generate(@discipline.py_filename, 'openmdao_discipline.py.erb', gendir)
      else
        raise DisciplineNotFoundException.new("Discipline " +
          discname + " not found in " + @mda.disciplines)
      end
    end
    
    def _generate(filename, template_filename, gendir)
      template = File.join(@template_dir, template_filename)
      Rails.logger.info "Creating #{filename} from #{File.basename(template)}"
      filepath = File.join(gendir, filename) if gendir      
      result = _comment_header(filepath)
      result += _run_template(template)
      fh = File.open(filepath, "w:utf-8") 
      fh.print result
      fh.close
      @genfiles << filepath if !@genfiles.include?(filepath)
      filepath
    end
    
    def _run_template(name)
      erb = ERB.new(File.open(name, "rb:utf-8").read, nil, '-')
      erb.result(binding)
    end
    
    def _comment_header(filepath)
<<HEADER
# -*- coding: UTF-8 -*-
"""
  #{File.basename(filepath)} generated by WhatsOpt 
"""
HEADER
    end
    
  end
  
end
